/* tslint:disable */
/* eslint-disable */
/**
 * ShafukuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    contents: string;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    rewards: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    orderer: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    endDate: string;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    numOfRecruit: number;
    /**
     * 
     * @type {Array<User>}
     * @memberof Task
     */
    assigners?: Array<User>;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "contents" in value;
    isInstance = isInstance && "rewards" in value;
    isInstance = isInstance && "orderer" in value;
    isInstance = isInstance && "endDate" in value;
    isInstance = isInstance && "numOfRecruit" in value;

    return isInstance;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': json['title'],
        'contents': json['contents'],
        'rewards': json['rewards'],
        'orderer': json['orderer'],
        'startDate': !exists(json, 'startDate') ? undefined : json['startDate'],
        'endDate': json['endDate'],
        'numOfRecruit': json['numOfRecruit'],
        'assigners': !exists(json, 'assigners') ? undefined : ((json['assigners'] as Array<any>).map(UserFromJSON)),
    };
}

export function TaskToJSON(value?: Task | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'contents': value.contents,
        'rewards': value.rewards,
        'orderer': value.orderer,
        'startDate': value.startDate,
        'endDate': value.endDate,
        'numOfRecruit': value.numOfRecruit,
        'assigners': value.assigners === undefined ? undefined : ((value.assigners as Array<any>).map(UserToJSON)),
    };
}

